<a href="https://colab.research.google.com/github/aliya-fatma011/Machine-Learning/blob/main/ml_day_1_rev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Load the Iris dataset and print:

#Number of samples
#Number of features
#Target names

In [1]:
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()

X = iris.data
y = iris.target

print("Number of samples:", X.shape[0])
print("Number of features:", X.shape[1])
print("Target names:", iris.target_names)

Number of samples: 150
Number of features: 4
Target names: ['setosa' 'versicolor' 'virginica']


In [ ]:
#Print:

#First 5 feature rows
#First 5 labels

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

print("First 5 Features:")
print(X[:5])

print("\nFirst 5 Labels:")
print(y[:5])

First 5 Features:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

First 5 Labels:
[0 0 0 0 0]


In [4]:
#split the Iris dataset into:

#80% Training
#20% Testing

#Print:

#Training shape
#Testing shape

In [5]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load dataset
iris = load_iris()

X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)
print("Training Labels Shape:", y_train.shape)
print("Testing Labels Shape:", y_test.shape)

Training Data Shape: (120, 4)
Testing Data Shape: (30, 4)
Training Labels Shape: (120,)
Testing Labels Shape: (30,)


In [ ]:
#Count how many samples belong to each class.

In [6]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()

y = iris.target

classes, counts = np.unique(y, return_counts=True)

for cls, count in zip(classes, counts):
    print(f"Class {cls}: {count} samples")

Class 0: 50 samples
Class 1: 50 samples
Class 2: 50 samples


or

In [7]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()

classes, counts = np.unique(iris.target, return_counts=True)

for cls, count in zip(classes, counts):
    print(f"{iris.target_names[cls]} : {count}")

setosa : 50
versicolor : 50
virginica : 50


In [ ]:
Function	Purpose
load_iris()	Load the Iris dataset
train_test_split()	Split data into training and testing sets
shape	Get the number of rows and columns
np.unique(..., return_counts=True)	Count samples in each class
X[:5]	Display the first 5 rows of features
y[:5]	Display the first 5 labels

In [10]:
import pandas as pd

# Create dataset
data = {
    "Name": ["Aliya", "Faisal", "Kriti", "Rahul", "Anjali"],
    "Age": [22, 23, 21, 24, 22],
    "Marks": [85, 90, 88, 76, 95]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print shape
print("Shape:", df.shape)

# Print column names
print("\nColumns:")
print(df.columns)

# Print first 5 rows
print("\nFirst 5 Rows:")
print(df.head())

Shape: (5, 3)

Columns:
Index(['Name', 'Age', 'Marks'], dtype='object')

First 5 Rows:
     Name  Age  Marks
0   Aliya   22     85
1  Faisal   23     90
2   Kriti   21     88
3   Rahul   24     76
4  Anjali   22     95


In [11]:
#Check Missing Values
import pandas as pd

data = {
    "Name": ["Aliya", "Faisal", "Kriti"],
    "Age": [22, None, 21],
    "Marks": [85, 90, None]
}

df = pd.DataFrame(data)

print(df)

print("\nMissing Values:")
print(df.isnull().sum())

     Name   Age  Marks
0   Aliya  22.0   85.0
1  Faisal   NaN   90.0
2   Kriti  21.0    NaN

Missing Values:
Name     0
Age      1
Marks    1
dtype: int64


In [12]:
#Fill Missing Values
import pandas as pd

data = {
    "Age": [22, None, 21],
    "Marks": [85, 90, None]
}

df = pd.DataFrame(data)

print("Before Filling:")
print(df)

# Fill missing values with mean
df.fillna(df.mean(numeric_only=True), inplace=True)

print("\nAfter Filling:")
print(df)

Before Filling:
    Age  Marks
0  22.0   85.0
1   NaN   90.0
2  21.0    NaN

After Filling:
    Age  Marks
0  22.0   85.0
1  21.5   90.0
2  21.0   87.5


#Remove Duplicate Rows

In [13]:
import pandas as pd

data = {
    "Name": ["Aliya", "Faisal", "Aliya", "Kriti"],
    "Marks": [85, 90, 85, 88]
}

df = pd.DataFrame(data)

print("Before Removing Duplicates:")
print(df)

print("\nShape:", df.shape)

# Remove duplicates
df = df.drop_duplicates()

print("\nAfter Removing Duplicates:")
print(df)

print("\nShape:", df.shape)

Before Removing Duplicates:
     Name  Marks
0   Aliya     85
1  Faisal     90
2   Aliya     85
3   Kriti     88

Shape: (4, 2)

After Removing Duplicates:
     Name  Marks
0   Aliya     85
1  Faisal     90
3   Kriti     88

Shape: (3, 2)


#label encoding

In [14]:
from sklearn.preprocessing import LabelEncoder

colors = ["Red", "Blue", "Green", "Red", "Blue"]

encoder = LabelEncoder()

encoded = encoder.fit_transform(colors)

print("Original Data:")
print(colors)

print("\nEncoded Data:")
print(encoded)

Original Data:
['Red', 'Blue', 'Green', 'Red', 'Blue']

Encoded Data:
[2 0 1 2 0]


In [ ]:
| Question | Function Used       | Purpose                        |
| -------- | ------------------- | ------------------------------ |
| 6        | `pd.read_csv()`     | Load a CSV file                |
| 7        | `isnull().sum()`    | Count missing values           |
| 8        | `fillna()`          | Fill missing values            |
| 9        | `drop_duplicates()` | Remove duplicate rows          |
| 10       | `LabelEncoder()`    | Convert text labels to numbers |
