<a href="https://colab.research.google.com/github/aliya-fatma011/Machine-Learning/blob/main/ml_day_1_numpyarrayrevise_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3])                 # 1D array
arr2 = np.array([[1, 2], [3, 4]])         # 2D array
arr_zeros = np.zeros((3, 4))              # Array of zeros
arr_ones = np.ones((2, 2))                # Array of ones
arr_range = np.arange(0, 10, 2)           # Array with a range of values
arr_linspace = np.linspace(0, 1, 5)       # Array with evenly spaced values

# Array attributes
print(f"Shape of arr2: {arr2.shape}")        # (rows, columns)
print(f"Dimensions of arr2: {arr2.ndim}")     # Number of dimensions
print(f"Data type of arr2: {arr2.dtype}")    # Data type of elements
print(f"Size of arr2: {arr2.size}")        # Total number of elements

# Array operations
addition = arr1 + arr1
multiplication = arr1 * 2
matrix_mult = np.dot(arr2, arr2) # Matrix multiplication

# Indexing and Slicing
print(arr1[0])          # First element
print(arr2[0, 1])       # Element at row 0, column 1
print(arr1[1:])         # Slice from second element to end
print(arr2[:, 0])       # All rows, first column

Shape of arr2: (2, 2)
Dimensions of arr2: 2
Data type of arr2: int64
Size of arr2: 4
1
2
[2 3]
[1 3]


In [3]:
# Reshaping
arr_reshaped = np.arange(9).reshape(3, 3)
print(f"Reshaped array:\n{arr_reshaped}")


Reshaped array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


1-D array

In [4]:
import numpy as np
a=np.array(['1','2','3'])
print(a)

['1' '2' '3']


In [5]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b=np.array(['a','l','i','y','a'])
print(b)

['a' 'l' 'i' 'y' 'a']


2.np.arange()

In [7]:
var='Aliya Fatma'
arr=np.arange(1,10)
print(arr)
print(var)

[1 2 3 4 5 6 7 8 9]
Aliya Fatma


In [8]:
arr2=np.arange(1,20,2,dtype=np.float32)
print(arr2)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


np.linspace()

In [9]:
arr=np.linspace(1,45,3)
print(arr)

[ 1. 23. 45.]


4. Using np.zeros()

In [10]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


np.ones()

In [11]:
arr=np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


using np.empty



In [12]:
arr=np.empty(5)
print(arr)

[3.20000076e+01 3.27680079e+04 1.04857625e+06 1.67772201e+07
 1.00663312e+08]


using np.full()

In [13]:
arr=np.full(5,100)
print(arr)

[100 100 100 100 100]


In [14]:
arr=np.random.rand(5)
print(arr)

[0.32373135 0.17529186 0.14785971 0.15300723 0.21789945]


In [15]:
arr=np.random.randint(1,100,5)
print(arr)

[ 2 53 90 64 24]


In [16]:
arr=np.random.uniform(1,100,5)
print(arr)

[64.65619849 11.41979504 34.46313268 91.65931044 77.60589703]


In [17]:
arr = np.logspace(1, 3, 5)

print(arr)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [18]:
arr = np.eye(5)[2]

print(arr)

[0. 0. 1. 0. 0.]


In [19]:
arr=np.eye(4)[2]
print(arr)

[0. 0. 1. 0.]


2-D array

In [20]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(arr.shape)

(3, 3)


In [22]:
print(arr.ndim)

2


In [23]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(3, 3)
9
int64


In [24]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
arr=np.ones((3,4))
print(arr
      )

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
arr = np.full((3,4),100)

print(arr)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


6. Using np.arange() + reshape()

In [27]:
arr = np.arange(1,13).reshape(3,4)

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
arr=np.arange(2,14)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13]


7. Using np.linspace() + reshape()

In [29]:
arr = np.linspace(10,100,12).reshape(3,4)

print(arr)

[[ 10.          18.18181818  26.36363636  34.54545455]
 [ 42.72727273  50.90909091  59.09090909  67.27272727]
 [ 75.45454545  83.63636364  91.81818182 100.        ]]


In [30]:
arr = np.identity(5)

print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Accessing Elements

In [31]:
arr=np.array([
    [10,20,30,40],
    [40,50,60,70],
    [70,80,90,100]
])

In [32]:
print(arr)

[[ 10  20  30  40]
 [ 40  50  60  70]
 [ 70  80  90 100]]


In [33]:
print(arr.shape)

(3, 4)


In [34]:
print(arr.ndim)

2


In [35]:
print(arr[1])

[40 50 60 70]


In [36]:
print(arr[1,2])

60


In [37]:
print(arr[-1,-1])

100


In [38]:
print(arr[:2])

[[10 20 30 40]
 [40 50 60 70]]


In [39]:
print(arr[:2])

[[10 20 30 40]
 [40 50 60 70]]


In [40]:
print(arr[1,:])

[40 50 60 70]


operation on 2-D array

In [41]:
import numpy as np

A = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[10 20 30]
 [40 50 60]]

Matrix B:
[[1 2 3]
 [4 5 6]]


In [42]:
c=A*B
print(c)

[[ 10  40  90]
 [160 250 360]]


In [44]:
c=A+B
print(c)

[[11 22 33]
 [44 55 66]]


In [43]:
c=A-B
print(c)

[[ 9 18 27]
 [36 45 54]]


In [45]:
c=A/B
print(c)

[[10. 10. 10.]
 [10. 10. 10.]]


In [46]:
result = A // B

print(result)

[[10 10 10]
 [10 10 10]]


In [47]:
result = A % B

print(result)

[[0 0 0]
 [0 0 0]]


In [48]:
result = A ** 2

print(result)

[[ 100  400  900]
 [1600 2500 3600]]


In [49]:
result = np.sqrt(A)

print(result)

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [50]:
result = np.cbrt(A)

print(result)

[[2.15443469 2.71441762 3.10723251]
 [3.41995189 3.6840315  3.91486764]]


In [51]:
print(np.max(A))

60


In [52]:
print(np.min(B))

1


In [53]:
print(np.sum(A))

210


In [54]:
print(np.mean(B))

3.5


In [55]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

result = A @ B

print(result)

[[19 22]
 [43 50]]


transpose

In [56]:
print(A.T)

[[1 3]
 [2 4]]


In [57]:
print(B.T)

[[5 7]
 [6 8]]


In [59]:
print(A.flatten())

[1 2 3 4]


In [60]:
A = np.array([
    [5,2,8],
    [7,1,3]
])

print(np.sort(A))

[[2 5 8]
 [1 3 7]]
